[package]
name = "snakes"
version = "0.1.0"
authors = ["iandanforth <iandanforth@gmail.com>"]

[dependencies]
piston = "0.35.0"
piston2d-graphics = "0.25.0"
pistoncore-glutin_window = "0.44.0"
piston2d-opengl_graphics = "0.51.0"
rand = "0.3.14"
